src/beans/apps/base/urls.py
from django.urls import path

from beans.apps.base.views import home_view, login_view, logout_view, register_view

urlpatterns = [
    path("", home_view, name="home"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("register/", register_view, name="register"),
]

src/beans/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("beans.apps.base.urls")),
    path("api/", include("beans.apps.coffee.api.urls")),
    path("coffees/", include("beans.apps.coffee.urls")),
    path("impex/", include("beans.apps.impex.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/beans/apps/base/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True, null=False)
    username = models.CharField(max_length=40, unique=False, null=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

src/beans/apps/coffee/models.py
from django.db import models

from beans.apps.base.models import User
from beans.apps.coffee.countries import get_country_by_name
from beans.generic_models import TimeStampedModel


class Processing(TimeStampedModel):
    constraints = [
        models.UniqueConstraint(
            fields=["user", "name"],
            name="unique_processing_constraint"
        )
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)


class Roaster(TimeStampedModel):
    constraints = [
        models.UniqueConstraint(
            fields=["user", "name", "country"],
            name="unique_roaster_constraint"
        )
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    country = models.CharField(max_length=80)
    website = models.URLField(null=True)

    class Meta:
        ordering = ("name", )

    @property
    def country_flag(self) -> str:
        if (country := get_country_by_name(self.country)) is None:
            return ""

        return country.unicode_flag


class TastingNote(TimeStampedModel):
    constraints = [
        models.UniqueConstraint(
            fields=["user", "name"],
            name="unique_tasting_note_constraint"
        )
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Coffee(TimeStampedModel):
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "name", "country", "roaster", "roasting_date", "processing"],
                name="unique_bean_roaster_constraint"
            )
        ]

    class Rating(models.IntegerChoices):
        VERY_GOOD = 5
        GOOD = 4
        OK = 3
        BAD = 2
        VERY_BAD = 1

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=False)
    country = models.CharField(max_length=80)
    processing = models.ForeignKey(Processing, on_delete=models.SET_NULL, null=True)
    roaster = models.ForeignKey(Roaster, on_delete=models.SET_NULL, null=True)
    roasting_date = models.DateField()
    rating = models.IntegerField(choices=Rating.choices, null=True)
    variety = models.CharField(max_length=200, null=True)
    tasting_notes = models.ManyToManyField(TastingNote)

    @property
    def country_flag(self) -> str:
        if (country := get_country_by_name(self.country)) is None:
            return ""

        return country.unicode_flag

    @property
    def tasting_notes_list(self) -> list[str]:
        if not self.tasting_notes.count():
            return []

        tasting_notes = []

        for note in self.tasting_notes.all():
            tasting_notes.append(note.name)

        return tasting_notes

src/beans/apps/base/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import User


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["email", "password1", "password2"]

src/beans/apps/base/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, redirect

from beans.apps.base.forms import RegistrationForm


def home_view(request: HttpRequest) -> HttpResponse:
    context = {
        "page": "home",
    }

    return render(request, "home.html", context=context)


def login_view(request: HttpRequest) -> HttpResponse:
    context = {"page": "login"}

    if request.user.is_authenticated:
        return redirect("home")

    if request.method == "POST":
        # TODO: add rate limiting
        email = request.POST.get("email").lower()
        password = request.POST.get("password")

        if (user := authenticate(request, email=email, password=password)) is not None:
            login(request, user)
            return redirect("home")
        else:
            messages.error(request, "Username or password incorrect")
            return render(request, "login_register.html", context=context)

    return render(request, "login_register.html", context=context)


@login_required(login_url="/login")
def logout_view(request: HttpRequest) -> HttpResponse:
    logout(request)
    return redirect("home")


def register_view(request: HttpRequest) -> HttpResponse:
    form = RegistrationForm()
    context = {
        "page": "register",
        "form": form,
    }

    if request.method == "POST":
        form = RegistrationForm(request.POST)

        if form.is_valid():
            user = form.save(commit=True)
            login(request, user)
            return redirect("home")
        else:
            context["form"] = form
            return render(request, "login_register.html", context=context)

    return render(request, "login_register.html", context=context)

src/beans/apps/base/templates/includes/aggregated_data_component.html
{% load queryset_tags %}
<div class="row">
    <div class="col-4">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">Coffees</h5>
                <p class="display-1">{{ request.user.coffee_set.count }}</p>
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">Origins</h5>
                <p class="display-1">{{ request.user.coffee_set|count_distinct_fields:"country" }}</p>
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">Roasters</h5>
                <p class="display-1">{{ request.user.roaster_set.count }}</p>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-6 gy-3">
        <div class="card" style="height: 100%;">
            <div class="card-header text-center">
                Top origins
            </div>
            <div class="card-body">
                <div class="text-left">
                    {% if request.user.coffee_set %}
                        <ol>
                            {% for item in request.user.coffee_set|get_most_common_origins:5 %}
                                <li>{{ item.origin }} (<span class="text-muted">{{ item.count }})</span></li>
                            {% endfor %}
                        </ol>
                    {% else %}
                        <p>No origins yet</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="col-6 gy-3">
        <div class="card" style="height: 100%;">
            <div class="card-header text-center">
                Top roasters
            </div>
            <div class="card-body">
                <div class="text-left">
                    {% if request.user.roaster_set %}
                        <ol>
                            {% for item in request.user.coffee_set|get_most_common_roasters:5 %}
                                <li>{{ item.roaster__name }} (<span class="text-muted">{{ item.count }})</span></li>
                            {% endfor %}
                        </ol>
                    {% else %}
                        <p>No roasters yet</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>